### ISSUE TITLE
F-Droid build recipe fix

### ISSUE THREAD

**Issue by dulvui** [Sajeg/falling-blocks#10]
Hello Sajeg,

I just saw that your game is also broken on F-Droid and mine was too. I used your F-Droid build recipe but on an update the game also broke.

Now I created a new working recipe that doesn't need a custom build folder, only the normal Godot project structure.
You can find the recipe here, its still not merged, but working.
https://gitlab.com/fdroid/fdroiddata/-/blob/b38f672bd2a45ef0b7a50981183d77fc7cae355f/metadata/com.simondalvai.ball2box.yml#L102

You would have to adapt some lines for your game, for example the prebuild steps.
But it should work then with no need of creating the custom build directory every time.

Let me know if you need any help!

**Comment by Sajeg** [comment]
Thank you very much ❤️. When I'm at home I'll have a look at it

**Comment by Sajeg** [comment]
At prebuild you have game/src/globals/Global.gd. What is this file? And why is it metioned at prebuild?

**Comment by dulvui** [comment]
This is just a config of my game so that some buttons work different for F-Droid builds. You can delete that line.
The only thing you need is a valid export_presets.cfg file with. The one I can see in your fdroid folder should work.

**Comment by Sajeg** [comment]
Thank you.

**Comment by Sajeg** [comment]
I have another question. He complains about missing x11 libraries. Can I ignore that?

**Comment by dulvui** [comment]
Yes that should not be a problem, because the Godot Editor then runs in headless mode without GUI, so no x11 libs are needed.
But if you want I can compare your pipeline run logs with mine. Just send me the link to your merge requests

**Comment by Sajeg** [comment]
Thank you again. The Pipelines are working. The result APK isn't signed, but that's right isn't it?

**Comment by Sajeg** [comment]
Thank you again. I'll close that now, because it's fixed.

**Comment by Sajeg** [comment]
The thing is on GitHub it always worked. That was an issue with F-Droid and that is now fixed and hopefully soon also in the Store.
