### ISSUE TITLE
Game doesn't start anymore (1.5)

### ISSUE THREAD

**Issue by manolol1** [Sajeg/falling-blocks#11]
I just updated the game to 1.5 using Fdroid. When I launch the game, I just see a black screen, then the app closes.

Device: Google Pixel 4
Android Version: 13

If you need further information, just tell me :)

**Comment by Sajeg** [comment]
Could you please go to the App info and check if it is 1.5.1 or just 1.5? Because on Fdroid I can see the Changelog, but not the version 1.5.1?

**Comment by Sajeg** [comment]
Alright, because I think there were an issue with uploading the APK to Fdroid.

**Comment by manolol1** [comment]
Just tried reinstalling the game and still got a black screen.
Also worth mentioning, that the whole phone is kinda buggy/laggy for a few seconds when I try to close the app. (animations are slow)

**Comment by Sajeg** [comment]
Alright. I hope that the Fdroid version will be working soon.

**Comment by manolol1** [comment]
It's working now.
