### ISSUE TITLE
Can't uninstall app from Samsung SM-A515W

### ISSUE THREAD

**Issue by TheCanuckdian** [Sajeg/falling-blocks#16]
I installed the app using the FDroid application, and now I can't remove it. Every time I choose to uninstall it hangs then times-out. I'm running the latest Samsung OS (Android 13). And ideas?

**Comment by Sajeg** [comment]
That's weird, but I don't think that it has something to do with my game.

**Comment by TheCanuckdian** [comment]
It's the only app I've seen that does this. Very weird. I'm going to try to force uninstall using ADB. I'll let you know if that works.

**Comment by Sajeg** [comment]
You can try this, but it's very weird, because I thought uninstalling is so deep integrated in android that a app can't  change anything at that.

**Comment by TheCanuckdian** [comment]
I was able to remove it with the ADB uninstall command. Issue closed.
