### ISSUE TITLE
Bug in color changing screen

### ISSUE THREAD

**Issue by GameOverFlowChart** [Sajeg/falling-blocks#17]
If I want to type a color code, as soon as I delete a character (or try to mark the whole text with the function of my keyboard) the screen turns completely black (the keyboard also disappears).

So I thought I use the sliders instead, but they seem to not go down enough so I can't make a color starting with 00 only 01 works (also using sliders is so much work in contrast to be able to paste a color code). So I gave up.

**Comment by Sajeg** [comment]
Thank you for reporting, but the sliders are working.

**Comment by GameOverFlowChart** [comment]
Might have to do with the screen size but I can't get it darker than 010101.  But I don't really care about the sliders if the text input gets fixed.

**Comment by Sajeg** [comment]
010101 is the smallest number that is possible. Later I'll look into the other issue

**Comment by GameOverFlowChart** [comment]
Yeah but let's say I want cyan which is 00ffff, I would have to use 01ffff instead because the sliders don't go further down. Can you reproduce the black screen? If not maybe it's a F-droid only problem again.

**Comment by Sajeg** [comment]
So I think I've fixed the issues. A line of code had crept in.
