### ISSUE TITLE
Block cosmetic shop

### ISSUE THREAD

**Issue by RageGamerBoi** [Sajeg/falling-blocks#19]
Maybe you could add a cosmetic block color shop where you can shop with your total collective points or some sort of high score or achievements based system similar to Sam Hogan's Stick With It (the mobile version)...

**Comment by Sajeg** [comment]
Yeah maybe I'll make this. This is similar to feature request #6

**Comment by Sajeg** [comment]
I think I'll not add this, because I already added the option too change the color of a block.
