### ISSUE TITLE
Can't seem to uninstall

### ISSUE THREAD

**Issue by ttoocs** [Sajeg/falling-blocks#21]
- Installed from fdroid
- can't seem to uninstall it, package installer keeps crashing
- tried to uninstall via fdroid and app-info, neither work

Not really sure how this is possible, half expect it to a bug with samsung's android..

**Comment by Sajeg** [comment]
Sorry, that you have issues with my game. Sadly I don't know why multiple people can't uninstall Falling Blocks. 

However you can solve this if you use adb to uninstall org.sajeg.fallingblocks .

Sorry for the inconveniences.

**Comment by ttoocs** [comment]
No worries, thank you for giving a solution! - Worked fine.

My best guess is that maybe something has a miss-matching name? Or maybe an Issue with godot? But not sure.

I'd grab logs of it myself if I could, but this particular phone is annoyingly locked-down and doesn't seem to have any related messages in the logcat output.

**Comment by Sajeg** [comment]
Yeah I think there is something wrong with the automated F-Droid compiling and Godot.
