### ISSUE TITLE
Update to Godot 3.5.3

### ISSUE THREAD

**Issue by licaon-kter** [Sajeg/falling-blocks#22]
ref: https://godotengine.org/article/maintenance-release-godot-3-5-3/

ref: https://blog.isosceles.com/the-webp-0day/

**Comment by licaon-kter** [comment]
Done https://gitlab.com/fdroid/fdroiddata/-/commit/b22dad8f0b624fadb3fe46e46e1ec4a1589d9644 thanks

**Comment by Sajeg** [comment]
Thank you too, for updating the recipe.
