### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by PDXUser** [Sajeg/falling-blocks#7]
I wanted to check the game out so I installed it  using F-Droid, when I  tried to uninstall, it keeps crashing my package manager now it is stuck on my phone.  

Can you please provide the adb command or a way to remove this from the phone manually?

**Comment by PDXUser** [comment]
Sajeg,

Thanks!  The command worked.    As for the game experience, nothing in my opinion to be improved, it was playable and enjoyable, I routinely test apps to see if they would be a good match for me, in this case, it was not.  Nothing personal against it or otherwise.   I am not a gamer, but curiosity got to me in this case. :) 

System Specs in case you were needing those - Android 13 on Galaxy A13 -5G.    Google play update to Jan 1 2023, and One UI 5.0 unrooted.

**Comment by Sajeg** [comment]
I can totally understand that. I like to try out apps too and tbh I'm not a big mobile gamer either.
