### ISSUE TITLE
Bug: Black screen

### ISSUE THREAD

**Issue by GameOverFlowChart** [Sajeg/falling-blocks#9]
Hi, thanks for implementing dark mode after my request, but since the update the game doesn't work for me anymore. I get a completely black screen.

**Comment by mrtaxi** [comment]
Android 11, that same issue

**Comment by Sajeg** [comment]
That's not great. I'll look in to it.

**Comment by mondlicht-und-sterne** [comment]
@Sajeg 

It is the same with me.

Android 13, Samsung S21 5G

**Comment by Sajeg** [comment]
That's strange.

**Comment by Sajeg** [comment]
Did you download it on GitHub or itch.io?

**Comment by Sajeg** [comment]
Did you download it on GitHub or itch.io? Now I know the Fdroid version is broken. I have an black screen too. I'll look into the issue.

**Comment by mondlicht-und-sterne** [comment]
on fdroid

**Comment by Sajeg** [comment]
Yes the Fdroid version is currently broken. I get an Black screen too.

**Comment by mrtaxi** [comment]
> That's not great. I'll look in to it. May I ask which phone you are using?

Onelpus 7, 12/256, android 11,

**Comment by GameOverFlowChart** [comment]
Yes I'm also on the f-droid version, and I'm using a Realme device with Android 13.

**Comment by Sajeg** [comment]
The new version should be online soon™ on F-Droid.
